completed spring-boot-web task
Ka1zerov/onlineBookStore pull request #3
Opened 2024-03-17 19:03 UTC by Ka1zerov

2024-03-18 10:26 UTC, Rommelua requested changes

2024-03-18 10:26 UTC, Rommelua commented on src/main/java/base/group/bookstore/model/Book.java
> +@Data
Do not use Data with Entities

2024-03-18 10:26 UTC, Rommelua commented on src/main/java/base/group/bookstore/service/BookServiceImpl.java
> +        existingBook.setCoverImage(bookDto.getCoverImage());
use mapper for this job

2024-03-19 12:01 UTC, kozhukhovsky approved these changes

2024-03-19 18:48 UTC, merged